In [1]:
# W1D1: Python for ML — NumPy Fundamentals

# Install NumPy
!pip install numpy pandas -q

# Import libraries
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Libraries imported successfully!")

NumPy version: 2.1.3
Pandas version: 2.2.3
Libraries imported successfully!


In [2]:
# Create a 1D NumPy array
array_1d = np.array([10, 20, 30, 40, 50])

# Create a 2D NumPy array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Create a 3D NumPy array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Display arrays
print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

print("\n3D Array:")
print(array_3d)

# Verify shapes
print("\nShapes:")
print("1D shape:", array_1d.shape)
print("2D shape:", array_2d.shape)
print("3D shape:", array_3d.shape)

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shapes:
1D shape: (5,)
2D shape: (2, 3)
3D shape: (2, 2, 2)


In [3]:
# Broadcasting example
marks = np.array([60, 70, 80, 90, 100])

bonus = 5

# NumPy automatically broadcasts 5 to every element
updated_marks = marks + bonus

print("Original marks:")
print(marks)

print("\nMarks after adding bonus:")
print(updated_marks)

Original marks:
[ 60  70  80  90 100]

Marks after adding bonus:
[ 65  75  85  95 105]


In [4]:
# Vectorised operations - no Python loops

scores = np.array([10, 20, 30, 40, 50])

print("Scores:", scores)
print("Scores × 2:", scores * 2)
print("Scores + 10:", scores + 10)
print("Scores squared:", scores ** 2)
print("Scores / 10:", scores / 10)

Scores: [10 20 30 40 50]
Scores × 2: [ 20  40  60  80 100]
Scores + 10: [20 30 40 50 60]
Scores squared: [ 100  400  900 1600 2500]
Scores / 10: [1. 2. 3. 4. 5.]


In [5]:
# Matrix multiplication

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = A @ B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nA @ B:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B:
[[19 22]
 [43 50]]


In [6]:
# Create a student performance dataset

data = {
    "Student_ID": range(1, 21),
    "Age": [18, 19, 18, 20, 19, 18, 21, 20, 19, 18,
            20, 21, 19, 18, 20, 19, 21, 20, 18, 19],
    "Math_Score": [78, 85, 67, 90, 72, 88, 95, 64, 76, 81,
                   69, 92, 74, 86, 79, 68, 91, 83, 71, 87],
    "Python_Score": [82, 89, 70, 94, 75, 91, 97, 68, 79, 85,
                     73, 95, 78, 90, 83, 71, 94, 88, 76, 92]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("student_performance.csv", index=False)

# Display first 10 records
print(df.head(10))

   Student_ID  Age  Math_Score  Python_Score
0           1   18          78            82
1           2   19          85            89
2           3   18          67            70
3           4   20          90            94
4           5   19          72            75
5           6   18          88            91
6           7   21          95            97
7           8   20          64            68
8           9   19          76            79
9          10   18          81            85


In [7]:
# Load the CSV dataset

df = pd.read_csv("student_performance.csv")

print("Dataset shape:", df.shape)

print("\nDataset:")
display(df)

Dataset shape: (20, 4)

Dataset:


,Student_ID,Age,Math_Score,Python_Score
0,1,18,78,82
1,2,19,85,89
2,3,18,67,70
3,4,20,90,94
4,5,19,72,75
5,6,18,88,91
6,7,21,95,97
7,8,20,64,68
8,9,19,76,79
9,10,18,81,85


In [8]:
# Convert score columns to NumPy arrays

math_scores = df["Math_Score"].to_numpy()
python_scores = df["Python_Score"].to_numpy()

print("Math scores:")
print(math_scores)

print("\nPython scores:")
print(python_scores)

Math scores:
[78 85 67 90 72 88 95 64 76 81 69 92 74 86 79 68 91 83 71 87]

Python scores:
[82 89 70 94 75 91 97 68 79 85 73 95 78 90 83 71 94 88 76 92]


In [9]:
# Convert score columns to NumPy arrays

math_scores = df["Math_Score"].to_numpy()
python_scores = df["Python_Score"].to_numpy()

print("Math scores:")
print(math_scores)

print("\nPython scores:")
print(python_scores)

Math scores:
[78 85 67 90 72 88 95 64 76 81 69 92 74 86 79 68 91 83 71 87]

Python scores:
[82 89 70 94 75 91 97 68 79 85 73 95 78 90 83 71 94 88 76 92]


In [10]:
# Calculate standard deviation using NumPy

math_std = np.std(math_scores)
python_std = np.std(python_scores)

print("Math Score Standard Deviation:", math_std)
print("Python Score Standard Deviation:", python_std)

Math Score Standard Deviation: 9.124691775616315
Python Score Standard Deviation: 9.024965373894794


In [11]:
# Calculate Pearson correlation using NumPy

correlation_matrix = np.corrcoef(math_scores, python_scores)

correlation = correlation_matrix[0, 1]

print("Correlation between Math and Python scores:", correlation)

Correlation between Math and Python scores: 0.9963566821754021
