In [1]:
# ============================================
# W1D3 SECTION 1: DATA LOADING
# ============================================

import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

# Create an Indian student performance dataset
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Aarav", "Priya", "Rahul", "Ananya", "Vikram",
        "Sneha", "Arjun", "Kavya", "Rohan", "Meera"
    ],
    "State": [
        "Karnataka", "Tamil Nadu", "Kerala", "Maharashtra",
        "Karnataka", "Kerala", "Tamil Nadu", "Karnataka",
        "Maharashtra", "Kerala"
    ],
    "Age": [20, 21, 20, 22, 21, 20, 23, 21, 22, 20],
    "Math_Score": [85, 90, 78, 88, 95, 82, 76, 91, 87, 89],
    "Python_Score": [88, 92, 80, 85, 94, 79, 74, 96, 83, 91]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save as CSV
df.to_csv("indian_student_data.csv", index=False)

# Load CSV using Pandas
df = pd.read_csv("indian_student_data.csv")

print("\nDataset loaded successfully!")
print("Shape:", df.shape)

print("\nFirst 10 rows:")
display(df.head(10))

NumPy version: 2.1.3
Pandas version: 2.2.3

Dataset loaded successfully!
Shape: (10, 6)

First 10 rows:


,Student_ID,Name,State,Age,Math_Score,Python_Score
0,101,Aarav,Karnataka,20,85,88
1,102,Priya,Tamil Nadu,21,90,92
2,103,Rahul,Kerala,20,78,80
3,104,Ananya,Maharashtra,22,88,85
4,105,Vikram,Karnataka,21,95,94
5,106,Sneha,Kerala,20,82,79
6,107,Arjun,Tamil Nadu,23,76,74
7,108,Kavya,Karnataka,21,91,96
8,109,Rohan,Maharashtra,22,87,83
9,110,Meera,Kerala,20,89,91


In [2]:
# ============================================
# W1D3 SECTION 2: DATA INSPECTION
# ============================================

print("DATA TYPES")
print("=" * 40)
print(df.dtypes)

print("\nDATASET INFORMATION")
print("=" * 40)
df.info()

print("\nSTATISTICAL SUMMARY")
print("=" * 40)
display(df.describe())

print("\nMISSING VALUES")
print("=" * 40)
print(df.isnull().sum())

print("\nDUPLICATE ROWS")
print("=" * 40)
print(df.duplicated().sum())

DATA TYPES
Student_ID       int64
Name            object
State           object
Age              int64
Math_Score       int64
Python_Score     int64
dtype: object

DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    10 non-null     int64 
 1   Name          10 non-null     object
 2   State         10 non-null     object
 3   Age           10 non-null     int64 
 4   Math_Score    10 non-null     int64 
 5   Python_Score  10 non-null     int64 
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

STATISTICAL SUMMARY


,Student_ID,Age,Math_Score,Python_Score
count,10.00000,10.000000,10.000000,10.00000
mean,105.50000,21.000000,86.100000,86.20000
std,3.02765,1.054093,5.933895,7.20802
min,101.00000,20.000000,76.000000,74.00000
25%,103.25000,20.000000,82.750000,80.75000
50%,105.50000,21.000000,87.500000,86.50000
75%,107.75000,21.750000,89.750000,91.75000
max,110.00000,23.000000,95.000000,96.00000



MISSING VALUES
Student_ID      0
Name            0
State           0
Age             0
Math_Score      0
Python_Score    0
dtype: int64

DUPLICATE ROWS
0


In [3]:
# ============================================
# W1D3 SECTION 3: DATA CLEANING
# ============================================

# Create a copy so the original data remains unchanged
cleaned_df = df.copy()

# Check missing values before cleaning
print("Missing values before cleaning:")
print(cleaned_df.isnull().sum())

# Remove duplicate rows
cleaned_df = cleaned_df.drop_duplicates()

# Remove rows containing missing values
cleaned_df = cleaned_df.dropna()

# Make sure numeric columns contain numeric values
cleaned_df["Age"] = pd.to_numeric(
    cleaned_df["Age"],
    errors="coerce"
)

cleaned_df["Math_Score"] = pd.to_numeric(
    cleaned_df["Math_Score"],
    errors="coerce"
)

cleaned_df["Python_Score"] = pd.to_numeric(
    cleaned_df["Python_Score"],
    errors="coerce"
)

# Remove any rows that became invalid
cleaned_df = cleaned_df.dropna()

print("\nData after cleaning:")
display(cleaned_df)

print("\nMissing values after cleaning:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows after cleaning:")
print(cleaned_df.duplicated().sum())

Missing values before cleaning:
Student_ID      0
Name            0
State           0
Age             0
Math_Score      0
Python_Score    0
dtype: int64

Data after cleaning:


,Student_ID,Name,State,Age,Math_Score,Python_Score
0,101,Aarav,Karnataka,20,85,88
1,102,Priya,Tamil Nadu,21,90,92
2,103,Rahul,Kerala,20,78,80
3,104,Ananya,Maharashtra,22,88,85
4,105,Vikram,Karnataka,21,95,94
5,106,Sneha,Kerala,20,82,79
6,107,Arjun,Tamil Nadu,23,76,74
7,108,Kavya,Karnataka,21,91,96
8,109,Rohan,Maharashtra,22,87,83
9,110,Meera,Kerala,20,89,91



Missing values after cleaning:
Student_ID      0
Name            0
State           0
Age             0
Math_Score      0
Python_Score    0
dtype: int64

Duplicate rows after cleaning:
0


In [4]:
# ============================================
# W1D3 SECTION 4: NUMPY OPERATIONS
# ============================================

# Convert Math scores to a NumPy array
math_scores = cleaned_df["Math_Score"].to_numpy()

print("NumPy Array:")
print(math_scores)

print("\nArray Shape:")
print(math_scores.shape)

print("\nArray Data Type:")
print(math_scores.dtype)

# SLICING
# Select the first five scores
first_five = math_scores[:5]

print("\nFirst five scores using slicing:")
print(first_five)

# BROADCASTING
# Add 5 bonus marks to every student's Math score
bonus_scores = math_scores + 5

print("\nScores after adding 5 bonus marks:")
print(bonus_scores)

# NumPy mathematical functions
print("\nMean Math Score:")
print(np.mean(math_scores))

print("\nMaximum Math Score:")
print(np.max(math_scores))

print("\nMinimum Math Score:")
print(np.min(math_scores))

print("\nStandard Deviation:")
print(np.std(math_scores))

NumPy Array:
[85 90 78 88 95 82 76 91 87 89]

Array Shape:
(10,)

Array Data Type:
int64

First five scores using slicing:
[85 90 78 88 95]

Scores after adding 5 bonus marks:
[ 90  95  83  93 100  87  81  96  92  94]

Mean Math Score:
86.1

Maximum Math Score:
95

Minimum Math Score:
76

Standard Deviation:
5.629387178015028


In [5]:
# ============================================
# W1D3 SECTION 5: TESTS AND FINAL VERIFICATION
# ============================================

# TEST 1: Check that DataFrame is not empty
assert not cleaned_df.empty, "DataFrame is empty!"

# TEST 2: Check required columns
required_columns = [
    "Student_ID",
    "Name",
    "State",
    "Age",
    "Math_Score",
    "Python_Score"
]

for column in required_columns:
    assert column in cleaned_df.columns, f"Missing column: {column}"

# TEST 3: Check for missing values
assert cleaned_df.isnull().sum().sum() == 0, \
    "Missing values still exist!"

# TEST 4: Check for duplicate rows
assert cleaned_df.duplicated().sum() == 0, \
    "Duplicate rows still exist!"

# TEST 5: Check NumPy array
assert isinstance(math_scores, np.ndarray), \
    "Math scores are not a NumPy array!"

print("All tests passed successfully!")

# Export cleaned dataset
cleaned_df.to_csv(
    "indian_student_data_cleaned.csv",
    index=False
)

print("\nCleaned dataset exported successfully!")

# Final summary
print("\n" + "=" * 50)
print("W1D3 - DATA LOADING, CLEANING & INSPECTION")
print("=" * 50)

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", cleaned_df.shape)
print("Number of students:", len(cleaned_df))
print("Average Math Score:", round(np.mean(math_scores), 2))
print("Average Python Score:",
      round(cleaned_df["Python_Score"].mean(), 2))

print("\nGenerated files:")
print("1. indian_student_data.csv")
print("2. indian_student_data_cleaned.csv")

print("\nW1D3 COMPLETED SUCCESSFULLY!")

All tests passed successfully!

Cleaned dataset exported successfully!

W1D3 - DATA LOADING, CLEANING & INSPECTION
Original dataset shape: (10, 6)
Cleaned dataset shape: (10, 6)
Number of students: 10
Average Math Score: 86.1
Average Python Score: 86.2

Generated files:
1. indian_student_data.csv
2. indian_student_data_cleaned.csv

W1D3 COMPLETED SUCCESSFULLY!
